site_name: deckster
theme: readthedocs
nav:
    - 'Index': 'index.md'
    - 'Installation': 'install.md'
    - 'Configuration': 'config.md'
    - 'Builtin Plugins': 'builtins.md'
    - 'Custom Plugins': 'plugins.md'
    - 'Changelog': 'changelog.md'
markdown_extensions:
  - mdx_truly_sane_lists